# Generated by Django 4.2.3 on 2023-07-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.message'),
        ),
    ]
