# Generated by Django 4.2.3 on 2023-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=150),
        ),
    ]
